micronaut:
  application:
    name: gallery
  server:
    port: 8080
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:h2:file:./gallery_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  flyway:
    enabled: true

javamail:
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        host: smtp.gmail.com
        port: 587
        ssl:
          trust: smtp.gmail.com
  username: nevenacrnogorac614@gmail.com
  password: ${SMTP_PASSWORD}

mail:
  from: nevenacrnogorac614@gmail.com

recaptcha:
  secret: ${RECAPTCHA_SECRET}
  url: https://www.google.com/recaptcha/api/siteverify

gallery:
  images-path: ${user.home}/gallery-images
